fastlane_version '2.103.0'
default_platform :ios

xc_project = 'ScrollViewLayout.xcodeproj'
tests_scheme = 'ScrollViewLayout'

platform :ios do

  desc 'Bootstrap project'
  lane :setup do
    carthage(
      platform: 'iOS',
      cache_builds: true
    )
  end

  desc 'Run tests'
  lane :test do
    scan(
      project: xc_project,
      scheme: tests_scheme
    )
  end

  desc 'Generate test coverage report in HTML format'
  lane :coverage_html do
    slather(
      proj: xc_project,
      scheme: tests_scheme,
      html: true,
      show: false,
      output_directory: 'coverage_report',
      verbose: true
    )
  end

end
