fastlane_version '2.103.0'
default_platform :ios

xc_project = 'ScrollViewLayout.xcodeproj'
tests_scheme = 'ScrollViewLayout'

platform :ios do

  desc 'Bootstrap project'
  lane :setup do
    carthage(platform: 'iOS')
  end

  desc 'Run tests'
  lane :test do
    scan(
      project: xc_project,
      scheme: tests_scheme
    )
  end

end
